# Generated by Django 5.0.7 on 2024-12-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_student_c_course_student_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
